name: front - build and deploy to linode

on:
  push:
    paths:
      - frontend/**

jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - run: HI! you changed something inside frontend right? 