name: front - build and deploy to linode

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy_to_linode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build